const express = require('express')
const app = express()
var morgan = require('morgan')
require('dotenv').config()
var fs = require('fs')
const port = process.env.PORT || 3500

//conexion orm a la base de sql server 
const knex = require("knex")({
  client: process.env.CLIENT_DATABASE,
  connection: {
    host : process.env.HOST,
    port : 1433,
    user : process.env.USER,
    password : process.env.PASSWORD,
    database : process.env.DATABASE,
    connectTimeout: 28 * 90000 // config para update masivos por hilo x 10mil registros
  },
  pool: { min: 1, max: 20 },
  acquireConnectionTimeout: 60 * 10000, // config para update masivos por hilo x 10mil registros
});
//listado profesiones
const profesion = ["TECNICO NAVAL", "DEPORTISTA", "ASESOR FINANCIERO", "ASISTENTE SOCIAL", "AGRICULTOR", "TECNOLOGO EN ALIMENTOS", "LIC. EN CIENCIAS SOCIALES", "MANICURISTA", "ABOGADA", "ADMINISTRADOR DE EMPRESA", "SOLDADOR", "ARQUITECTO", "MILITAR RETIRADO", "LIC.CONTABILIDAD Y ADM.", "TÉCNICO EN REFRIGERACIÓN", "LIC. EN QUIMICA", "TERAPEUTA", "TEC. ELECTROMECANICO", "AUXILIAR DE ENFERMERIA", "DISEÑADOR GRAFICO", "CHEFF", "GOMERO", "INFORMATICO", "TEC. SUP. EN CONST. CIVIL", "CONSTRUCTOR", "BACHILLER CONTABLE", "LIC. EN RADIOLOGÍA", "COSTURERA", "PILOTO CIVIL", "TECNICO EN OBSTETRICIA", "MARMOLISTA", "PSICOLOGO/A", "INGENIERO CONSTRUCTOR", "TEJEDORA DE ÑANDUTI", "MILITAR", "INGENIERO EN INFORMATICA", "TECNICO EN MICRO COMPUTADORAS", "EMPLEADO BANCARIO", "LIC. EN BIBLIOTECOLOGIA", "ELASTIQUERIA", "LIC.EN CIENC.CONT.Y ADM.", "TECNICO AGRONOMO", "PASTOR", "TECNICO DE FUTBOL", "MASTER EN MARKETING", "COSMETOLOGO", "EMPRESARIO", "CONTADOR", "CARNICERO", "ELECTROTECNICA", "TEC. EN MANT. DE EQUIPOS BIOMEDICOS", "JOCKEY", "TECNICO EN TRANSITO AEREO", "SUPERVISOR", "AGROPECUARIO", "ESTANCIERO", "AGENTE MARITIMO", "QUIMICO", "SOLDADOR ELECTRICO", "METALURGICO", "MARINO MERCANTE", "DOCENTE", "LIC. EN LABORATORIO CLINICO", "SASTRE", "CITOTECNOLOGO", "INGENIERO", "PROFESOR", "AGRONOMO", "INGENIERO TELECOMUNICACION", "TECNICO", "INGENIERO FORESTAL", "CANTANTE", "ARTESANO", "LIC. EN C.DE COMUNICACION", "PROF. EDUCACION FISICA", "AGENTE TECNICO AGROPECUARIO", "PROPIETARIO", "AGENTE DE CAMBIO", "VISITADOR/A MEDICO", "TORNERO MECANICO", "RADIOLOGO", "TECNICO VIA CARRETERA", "LIC. EN PERIODISMO", "LIC.EN ENF.Y OBSTETRIC.", "VIDRIERO", "TECNICO EN COMUNICACION", "GASTRONOMICO", "PRESIDENTE DE SOCIEDAD", "MEDICO VETERINARIO", "GRAFICO", "PINTOR DE AUTOMOVIL", "TECNICO FORESTAL", "SECRETARIA", "BOMBERO", "MECANICO INDUSTRIAL", "INGENIERO BIOMEDICO", "ARMADOR", "QUIMICO FARMACEUTICO", "LIC. EN IDIOMA", "CARPINTERO", "PROF. DE ARTE CULINARIO", "LIC.CIENCIAS COMERCIALES", "QUIMICO ANALITICO", "TECNICO MECANICO", "LIC.EN TEC.DE PRODUCCION", "CERRAJERO", "ANALISTA INDUSTRIAL", "HERRERO", "ELEC. DE AUTOMOVIL", "CHAPISTA", "EMPLEADA DOMESTICA", "INGENIERO ELECTRONICO", "LIC. EN ENFERMERIA", "DIRECTOR", "DR. BIOQUIMICO", "DOCENTE - JUBILADO", "CALDERERO", "COMISIONISTA", "MASTER EN ADM.DE EMPRESAS", "SECRETARIO RECEPCIONISTA", "BIOQUIMICO", "AUXILIAR DE FARMACIA", "PROF. DE DANZA", "VETERINARIO", "ABOGADO - JUBILADO", "TECNICO EN LABORATORIO", "IDONEO EN FARMACIA", "JUBILADO", "DIPLOMATICO", "TECNICO ANESTECISTA", "NOTARIO PUBLICO", "GERENTE DE VENTAS", "BACHILLER EN ADMINISTRACION", "OPERADOR DE TERMINAL", "INGENIERO AGRONOMO", "FUNCIONARIO", "LIC.CIENCIAS GEOGRAFICAS", "RELIGIOSO", "PSICOPEDAGOGO", "LIC.CIENCIAS CONTABLES", "TEC. EN ELECTROTECNICA", "MODISTA", "TRANSPORTISTA", "MEDICO NATURALISTA", "GERENTE ADMINISTRATIVO", "INGENIERO AMBIENTAL", "PILOTO ULTRAMAR", "DESPACHANTE DE ADUANA", "ASESOR TECNICO", "NAVEGANTE", "TECNICO INDUSTRIAL", "DR.CIENCIAS ECONOMICAS", "DACTILOGRAFO", "JORNALERO", "VENDEDOR", "EJECUTIVO", "LIC.EN CIENC.DE LA EDUC.", "FARMACEUTICO", "LIC.RELACIONES PUBLICAS", "INGENIERO INDUSTRIAL", "TECNICO SUP. RADIOLOGIA", "TEJEDOR", "GEOGRAFO", "PROF. DE MUSICA", "CAPITAN DE CABOTAGE", "EMPLEADO", "ADMINISTRADOR", "MECANICO DE AVIACION", "INDUSTRIAL", "INGENIERO NAVAL", "INGENIERO QUIMICO", "OPERADOR DE COMPUTADORA", "HACENDADO", "SECRETARIA EJECUTIVA", "DISEÑADOR", "INGENIERO ELECTROMECANICO", "AGENTE DE VIAJE", "COMERCIANTE", "TECNICO RADIOLOGO", "MEC. DE AUTOMOTRIZ", "GESTOR", "IDONEO EN VETERINARIA", "ESCULTOR", "TECNICO INSTRU.QUIRURGICO", "TECNICO EN PROTESIS DENTAL", "FISIOTERAPEUTA", "LIC. EN DIPLOMACIA", "AGENTE DE SEGURO", "CAPATAZ", "TECNICO MONTADOR DE AVION", "TRACTORISTA", "LIC. ADMINIS.AGRARIA", "LIC. EN LENGUA INGLESA", "LABORATORISTA", "TAPISERO", "HOTELERO COMERCIAL", "PASTOR EVANGELICO", "COCINERO", "INSTRUMENTADOR QUIRURGICO", "OBISPO", "LIC. EN LETRAS", "MAESTRA JARDINERA", "MODELO", "ASISTENTE DE GERENTE", "EDUCADOR", "OFICIAL DE JUSTICIA", "REFLEXOTERAPEUTA", "PELUQUERO", "JARDINERO", "LETRISTA", "ARTISTA", "LIC. EN SERVICIO SOCIAL", "AUXILIAR CONTABLE", "PUBLICISTA", "AGENTE POLICIA", "ESCRIBANO/A", "DIBUJANTE TECNICO", "TECNICO EN COMPUTACION", "TECNICO ELECTRICISTA", "ENFERMERO", "MISIONERO", "INGENIERO METALURGICO", "TIPOGRAFO", "TEC. HIDRAULICO", "INSEMINADOR", "AZAFATA", "LIC.ADM.Y GERENCIA EMPRESA", "DIRECTOR TECNICO", "DECORADOR", "ADIESTRADOR", "COBRADOR", "LIC. EN TEOLOGIA", "ALBAÑIL", "NOTARIO Y ESC. PUBLICO", "LIC. EN HISTORIA", "TAXISTA", "BANCARIO", "ELECTRONICO", "MEDICO CIRUJANO", "EMPLEADO COMERCIAL", "LIC. EN CIENC. DEL DEPORTE", "ECONOMISTA", "LIC.EN PSICOLOGIA", "CONTRATISTA", "AUXILIAR DE LABORATOIO", "INGENIERO ELECTRICISTA", "DR. EN ADMINISTRACION", "GERENTE COMERCIAL", "PROF. DE GUITARRA", "ABOGADO - DOCENTE", "TRADUCTOR", "LIC. EN MATEMATICA", "DR. CIENCIAS VETERINARIA", "TECNICO OPTICO", "PILOTO AVIADOR", "OBRAJERO", "MOZO", "ARMADOR DE HIERRO", "LIC. EN FILOSOFIA", "CONTADOR PUBLICO", "IMPRESOR", "LIC. EN CONTABILIDAD", "RELOJERO", "INGENIERO COMERCIAL", "MUSICO", "INGENIERO DE SISTEMAS", "OPERADOR", "INGENIERO GEOGRAFO", "TECNICO QUIMICO", "TECNICO REFRIGERACION", "ELECTROMECANICO", "MEDICO/A", "FUTBOLISTA", "PINTOR", "TOPOGRAFO", "LIC. EN ADMINISTRACION", "PROF. EN CORTE Y CONFEC.", "FONOAUDIOLOGO", "PLANAGRAFISTA", "POLICIA", "GRANJERO", "LIC. EN OBETRICIA", "CONFECCIONISTA", "OBSTETRA", "TECNICO EN PRODUCCION", "YESERO", "LOCUTOR", "CORTADOR TEXTIL", "INGENIERO MECANICO", "TECNICO EN TELEVISION", "HORTICULTOR", "LIC. EN ANALISTA DE SISTEMAS", "INGENIERO CIVIL", "MAESTRO MAYOR DE OBRA", "ANTROPOLOGO", "ESTUDIANTE", "FOTOGRAFO", "ODONTOLOGO", "TECNICO EN ENFERMERÍA", "PROF. DE INGLES", "TECNICO EN FARMACIA", "AZULEJISTA", "PILOTO", "INGENIERO HIDRAULICO", "LIC.CIENCIAS BIOLOGICAS", "ING.MECANICO ELECTRICISTA", "JEFE DE TALLER", "SACERDOTE", "ELECTRICISTA", "COORDINADOR DE IMPUESTOS", "C3745522", "FUNCIONARIO PUBLICO", "estudio contable", "PROFESIONAL INDEPENDIENTE", "MECANICO DENTAL", "LIC. EN KINESIOLOGIA", "CAMBISTA", "COOPERATIVA", "LIC. EN ADM. DE EMPRESA", "EDITOR DE TELEVISION", "TECNICO ELECTRONICO", "PERIODISTA", "BOBINADOR", "OPERARIO DE MAQUINA", "INVESTIGADOR CIENTIFICO", "AGENTE INMOBILARIO", "GERENTE", "CONSULTOR", "CHOFER", "ANESTESISTA", "TECNICO GANADERO", "ARTE PLASTICO", "TORNERO", "AMA DE CASA", "ALFARERO", "LIC. EN COMPUTACION", "AUDITOR", "QUIMICO INDUSTRIAL", "ZAPATERO", "AUX. DESPACHANTE", "OPTICO", "AGENTE DE VENTA", "PROG. DE COMPUTADORA", "ESTIBADOR", "GANADERO", "GEOLOGO", "FAENA FORESTAL", "RADIO TECNICO", "ANALISTA DE SISTEMAS", "DR. EN QUIMICA INDUSTRIAL", "TEC. AGROMECANICO", "JOYERO", "MAQUINISTA", "LIC.EN COMERCIO EXTERIOR", "TEC.AGROPECUARIO FORESTAL", "INGENIERO GRAFICO", "DIBUJANTE", "ENCARGADO", "LICENCIADO", "LIC. EN PUBLICIDAD Y MARKETING", "PLOMERO", "BIOLOGO", "TECNICO SUP. DE ELECTRICIDAD", "IMPORTADOR", "PRODUCTOR DE T.V.", "MECANICO", "INGENIERO GEOLOGO", "TECNICO AGROPECUARIO", "DR. EN PSICOLOGIA", "RADIO OPERADOR", "ESTILISTA", "TECNICO VIAL", "TECNICO CONTABILIDAD", "PANADERO", "NUTRICIONISTA", "TRABAJADOR SOCIAL", "TECNOLOGO MEDICO", "PINTOR DE OBRAS", "JEFE DE PRODUCCION", "OBRERO", "PROMOTOR DE VENTA", "TECNICO SUPERIOR", "MASAJISTA", "MOLINERO", "LIC. EN COMERCIO EXTERIOR"]
const init = async() =>{
  let res = await knex.select().table(process.env.TABLE).limit(10) //ejecutar de a 10mil registros para consumir mucho recurso del servidor .where('item', '>', 22351)//.limit(10)
  console.log(res)// para ver los datos de la base 
  let dato ='', valor = '';

  const lista = res //res.map(item => item.texto )
  let matriz = []
  console.log('===================================================================')
  //recorremos la lista de solicitudes 
  lista.forEach((item, index) =>{
    item.texto.split(' ').forEach((item2) =>{//por cada palabra del texto macheamos con el array de profesiones 
      if(item2.length > 6 ){
        dato = profesion.find(item3=> item3.toLowerCase().slice(0,7) === item2.toLowerCase().slice(0,7) )//macheamos con profesiones con rango de 7 caracteres posibles
        if(dato != undefined){//si encontro profesiones agregar al listado de macheo x solicitud 
          if(!valor.includes(`${dato}`)){//solo valores unicos de profesiones no deberia repetir la profesion x solicitud 
            valor += `${dato} (${item2.toLowerCase()}) - `
          }
          console.log(`fila ${index} - ${dato} - ${item2}`)
        }
      }
    })
    console.log('siguiente texto ', index )
    console.log('profesiones: ', valor)
    matriz.push({solicitud: item.solicitud , profesion: valor})
    valor = ''

  })
  console.log(matriz)

  ////////////////////////////////////////////////////////////////
  //para actualizar la base datos con los datos macheados 
  matriz.forEach(async item => {
    ////////////////////////////////////////
    try {
      await knex(process.env.TABLE)
      .update({profesion: item.profesion})
      .where('solicitud', item.solicitud)
      .then((e)=>{
        console.log('actualizo ' , item.solicitud)
      })
    } catch (error) {
      console.log('hubo un error con la base: ', error)
    }
  })
}

//iniciamos el proceso cuando arranca el servicio 
init()

app.use(morgan('combined'))
app.get('/', (req, res) => {
  res.send('profesion server ')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})

